name: hookups
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  bubble_tab_indicator: ^0.1.3
  cached_network_image: ^0.5.0+1
  page_indicator: ^0.1.0
  page_view_indicator: ^0.3.0+1
  flutter_masked_text:
  font_awesome_flutter: ^8.2.0
  #swipable: ^0.1.0
  swipedetector: ^1.2.0
  flutter_swiper: ^1.1.4
  fluttery_dart2: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/app_icon.png
    - assets/images/ava6.png

    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/hookup.png
    - assets/images/swipe.png
    - assets/images/match.png
    - assets/images/avatar.jpg
    - assets/images/chat2.png
    - assets/images/ic_chat.png
    - assets/images/hookup_icon.png
    - assets/images/hookup_icon_small.png
    - assets/images/lightening.png


  fonts:
      - family: Quicksand
        fonts:
          - asset: assets/fonts/Quicksand-Medium.ttf
            style: normal
          - asset: assets/fonts/Quicksand_Bold.otf
            weight: 700


      - family: Raleway
        fonts:
          - asset: assets/fonts/Raleway-Regular.ttf
            style: normal
          - asset: assets/fonts/Raleway-Medium.ttf

      - family: Nirmala
        fonts:
          - asset: assets/fonts/Nirmala.ttf
      - family: ProximaNovaSoft
        fonts:
          - asset: assets/fonts/ProximaNovaSoft-Regular.otf
            style: normal
          - asset: assets/fonts/ProximaNovaSoft-Semibold.otf
            style: normal
          - asset: assets/fonts/ProximaNovaSoft-Bold.otf
            weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
